import { StyleSheet } from 'react-native';
import { ROLE_COLORS, SURFACE_MUTED, TEXT_DARK, TEXT_MUTED, UI } from '@/constants/ui';

export const TAILOR = {
  ...ROLE_COLORS.tailor,
  screenBg: SURFACE_MUTED,
  text: TEXT_DARK,
  textMuted: TEXT_MUTED,
  headerGradientTop: '#fda4af',
  headerGradientBottom: ROLE_COLORS.tailor.primary,
  chipBg: '#fdf2f8',
  chipText: '#831843',
  successSoft: '#ecfdf5',
  successText: '#047857',
  warningSoft: '#fff7ed',
  warningText: '#c2410c',
};

export const tailorStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: TAILOR.screenBg,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 100,
  },
  headerPanel: {
    backgroundColor: TAILOR.primary,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    paddingTop: 12,
    paddingBottom: 22,
    paddingHorizontal: 16,
    marginBottom: 4,
    overflow: 'hidden',
    ...UI.shadow,
  },
  headerGlow: {
    position: 'absolute',
    top: -40,
    right: -30,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  headerGlowSmall: {
    position: 'absolute',
    bottom: -20,
    left: -20,
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  backBtn: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    color: 'rgba(255,255,255,0.88)',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 6,
    maxWidth: '95%',
  },
  infoBanner: {
    backgroundColor: TAILOR.soft,
    borderWidth: 1,
    borderColor: TAILOR.border,
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
  },
  infoBannerText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 19,
    color: TEXT_MUTED,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: TAILOR.border,
    padding: 16,
    marginBottom: 12,
    ...UI.softShadow,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: TEXT_DARK,
    marginBottom: 10,
  },
  emptyWrap: {
    alignItems: 'center',
    paddingVertical: 36,
    paddingHorizontal: 20,
  },
  emptyIcon: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: TAILOR.soft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: TEXT_DARK,
    marginBottom: 6,
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 13,
    lineHeight: 19,
    color: TEXT_MUTED,
    textAlign: 'center',
  },
  primaryBtn: {
    backgroundColor: TEXT_DARK,
    paddingVertical: 13,
    borderRadius: 14,
    alignItems: 'center',
    ...UI.softShadow,
  },
  primaryBtnText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 13,
  },
  secondaryBtn: {
    paddingVertical: 13,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: TAILOR.border,
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  secondaryBtnText: {
    fontWeight: '800',
    fontSize: 13,
    color: TEXT_DARK,
  },
});
